spring.application.name=api-gateway

server.port=8087

spring.cloud.gateway.routes[0].id=student-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/students/**

spring.cloud.gateway.routes[1].id=teacher-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/teachers/**

spring.cloud.gateway.routes[2].id=library-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/books/**books/**